backend:
  name: github
  repo: vikatgen/tugikeskus-netlify-cms
  branch: master

media_folder: "/static/img/"
public_folder: "/img/"

collections:
  - name: "blog"
    label: "Blogi"
    format: "json"
    folder: "assets/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Pealkiri", name: "title", widget: "string" }
      - { label: "Kuupäev", name: "date", widget: "datetime" }
      - { label: "Lühikirjeldus", name: "description", widget: "string" }
      - {
          label: "Kas läheb esilehele?",
          name: "draft",
          widget: "boolean",
          default: false,
        }
      - { label: "Sisu", name: "body", widget: "markdown" }
      - { label: "Pilt", name: "thumbnail", widget: "image" }
  - name: "workers"
    label: "Töötajad"
    format: "json"
    folder: "assets/content/contacts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Nimi", name: "name", widget: "string" }
      - {
          label: "Vali kategooria",
          name: "job-category",
          widget: "select",
          options:
            - { label: "Juhtimine", value: "juhtimine" }
            - { label: "Psühholoogid", value: "psühholoogid" }
            - { label: "Eripedagoogid", value: "eripedagoogid" }
            - { label: "Logopeedid", value: "logopeedid" }
            - { label: "Sotsiaalpedagoogid", value: "sotsiaalpedagoogid" }
            - { label: "Juhtumikorraldajad", value: "juhtumikorraldajad" }
            - { label: "Peretöötajad", value: "peretöötajad" }
        }
      - { label: "Amet", name: "occupation", widget: "string" }
      - { label: "Seletus", name: "occupation-description", widget: "string" }
      - { label: "Telefoni number", name: "phone-number", widget: "number" }
      - { label: "Emaili aadress", name: "email-address", widget: "string" }
